### ISSUE TITLE
nouvelle colonne pour savoir si on a accepté les cgu

### ISSUE THREAD

**Issue by CorentinAT** [SerrataApp/serrata_api#40]

**Comment by CorentinAT** [comment]
Avec une requete pour les accepter en etant connecté, et une requete pour remettre tout le monde "False" en tant qu'admin

**Comment by TangoCh4rlie** [comment]
> Avec une requete pour les accepter en etant connecté, et une requete pour remettre tout le monde "False" en tant qu'admin

Lorsque tu change les CGU??

**Comment by CorentinAT** [comment]
oui quand je change les CGU je veux pouvoir mettre tout le monde à False pour qu'ils doivent ré-accepter
