### ISSUE TITLE
quand on passe une partie en public, toutes les autres parties dans ce mode de jeu (de ce user) passent en privé

### ISSUE THREAD

**Issue by CorentinAT** [SerrataApp/serrata_api#41]

**Comment by TangoCh4rlie** [comment]
T'es sur que c'est pas à faire dans le front ca??
Et genre t'appelle un l'endpoint pour chaque partie?
C'est surrement plus brodelique?

**Comment by CorentinAT** [comment]
possible dans le front, je le fais pour le moment, mais ça fait 3 requetes à faire contre 1 si c'est dans le back
